--
-- Contenu de la table `BOTSECTOR_CRAWLERS`
--

INSERT IGNORE INTO `BOTSECTOR_CRAWLERS` (`BCR_ID`, `BCR_NAME`, `BCR_SIGNATURE`, `BCR_WEBSITE`) VALUES
(1, 'Standard Browser', '-- NOTE: these are regular expressions!\r\n\r\n-- Generic keywords:\r\n-\r\nUSER_AGENT\r\nUnknown\r\ncompatible\r\nlike Gecko\r\nLike Gecko\r\ncomme Gecko\r\nlike Firefox/0\r\nKHTML\r\n\r\n-- Versions:\r\n0\r\nVersion/0\r\nVersion/0.EU\r\nrv:0\r\nrv:0a0\r\nVER#[A-Z0]+#0\r\n\r\n-- Languages:\r\n[a-z]{2}-?\r\n[a-z]{2}-[A-Z]{2}\r\n[A-Za-z]{2}_[A-Z]{2}\r\nFRCH\r\nFRFR\r\nFRCA\r\nFRBE\r\n[A-Z]{4}(MS[EN]|WOL)\r\nDEDE\r\nENUS\r\n\r\n-- Strange signatures:\r\n-- Enable again to match all? [A-Z]{1,9}0?\r\nWOW0\r\nSLCC0\r\nMA[A-Z0]{2}\r\nMA[A-Z0]{2} Runtime\r\n[AM][A-Z0]{3}JS\r\nBLNGBAR\r\nGTB0\r\nBTRS0\r\nBOIE0\r\nYTB0\r\nEIE0\r\nWMDRMPD: 0\r\nFBSMTWB\r\n[A-Z]{3}TDF\r\nXBLWP0\r\nPLIMPOT\r\nTERA\r\nASJB\r\nLCJB\r\nOPENC\r\n\r\n-- OS and CPU:\r\nMicrosoft\r\nWindows\r\nWindows NT 0\r\nWin0\r\nWindows CE\r\nWindows Mobile\r\nWindows Phone 0\r\nWindows Phone OS 0\r\nWinNT-[A-Z0]{3} 0\r\nWindows Phone 0[A-Z] by HTC\r\nwds 0\r\n\\.NET CLR 0\r\n\\.NET0[A-F]\r\n\\.NET Client 0\r\nLinux\r\nLinux x0\r\nLinux i0\r\nLinux i0 on x0\r\nLinux mips\r\nLinux armv0l\r\nLinux zvav\r\nUbuntu\r\nUbuntu/0\r\nAustin Linux/0\r\nc\r\nU\r\nx0\r\nX0\r\nGUI\r\nlike iPhone OS 0 Mac OS X\r\nMacintosh\r\nIntel Mac OS X\r\nIntel Mac OS X 0\r\nCPU iPhone OS 0 like Mac OS X\r\nCPU OS 0 like Mac OS X\r\nCPU like Mac OS X\r\nPPC Mac OS X\r\nPPC Mac OS X 0\r\nMac_PowerPC\r\nCrOS i0 0\r\nCrOS/0\r\nCrOS armv0l 0\r\nCriOS/0\r\nCrOS x0 0\r\nAndroid\r\nAndroid 0\r\nAndroid 0-update0\r\nAdr 0\r\nAdr 0-update0\r\n[A-Za-z0\\/\\-_ \\.\\'']+ Build/[A-Za-z0_\\-\\. ]+\r\nBuild/[A-Z0]+\r\nCyanogenMod-0\r\nCyanogenMod/0/[a-z0]+\r\nARM\r\nSymbian\r\nSymbian/0\r\nSymbianOS/0\r\nJava\r\nJava/ASVM/0\r\nWQVGA\r\nWVGA\r\nHVGA\r\nwebOS/0\r\nhpwOS/0\r\nSUSE/0-0\r\nMandriva/0-0mdv0\r\nmaverick\r\nkarmic\r\nlucid\r\nhardy\r\nQt/0\r\nQtv0\r\n\r\n-- Devices:\r\niPhone\r\niPad\r\niPod\r\niPod touch\r\nTablet\r\nTablet PC 0\r\nhp-tablet\r\nRIM Tablet OS 0\r\nBB0\r\nBlackBerry\r\nBlackBerry 0\r\nBlackBerry0/0\r\nMedia Center PC 0\r\nTouch\r\nZuneWP0\r\nZune 0\r\nOpera Tablet/ADR-0\r\n\r\n-- Browsers/Engines:\r\nMSIE0\r\nMSIE 0\r\nMSIE 0b0\r\nIE0_ver0\r\nIEMobile/0\r\nIEMobile 0\r\nTrident/0\r\nEdge/0\r\nMozilla/0\r\nAppleWebKit/0\r\nAppleWebkit/0\r\nApple WebKit/0\r\nChrome\r\nChrome/0\r\nChromium/0\r\nUbuntu Chromium/0\r\nFirefox/0\r\nFirefox/0a0\r\nSafari/0\r\nSafari/0/[d\\.m0]+\r\nTabletSafari/0\r\nGecko/0\r\nBeamrise/0\r\nFennec/0\r\nMercury/0\r\nOpera/0\r\nOPR/0\r\nOpera Mobi/ADR-0\r\nOpera Mini/0/0\r\nOpera Mini/att/0\r\nPresto/0\r\nCamino/0\r\nMaxthon\r\nMaxthon 0\r\nMaxthon/0\r\nDolfin/0\r\nIceape/0\r\nOPiOS/0\r\n\r\n-- Mobiles:\r\nMobile\r\nMobile/0\r\nMobile/0[a-z]\r\nMobile/0[A-Z]0[a-z]?\r\nHTC\r\nHTC_DesireHD_A0\r\nHTC_HD0_T0\r\nHTC0LVW\r\nSAMSUNG\r\nSAMSUNG(?:-[A-Z]{2,3}-[A-Z0]*/[A-Z0]+|-[A-Z]{2,3}-[A-Z0]+-[A-Za-z]+/[A-Z0]+|.(GT|SM)-[A-Z]0[A-Z]?)\r\nsamsung-gt-s0\r\nSamsungBrowser/0\r\ngt-s0\r\nSGH-i0R\r\nGT-[A-Z]0i?\r\nNOKIA\r\nNokia0XpressMusic/0\r\nSeries ?0\r\nNokia[A-Z]0\r\nNokia[A-Z]0-0(/0)?\r\nNokia0c-0\r\nSeries0/0 Nokia[A-Fa-f0\\-]+/0\r\nNokia0/0\r\nNokia0\r\n[nN]okia ?[nN]?0\r\nNokiaBrowser/0\r\nLumia 0\r\nLumia 0 NFC\r\nLumia 0 Dual SIM\r\nLumia 0 LTE\r\nLumia 0 LTE Dual SIM\r\nlg-c0\r\nLG-[A-Z]0\r\nLG-GS0/V0\r\nLG-BL0/v0a\r\nWidget/LGMW/0\r\nMMS/LG-MMS-V0/0\r\nMMS/LG-Android-MMS-V0\r\nMMS/LG-Android-MMS-V0/0\r\nsonyericsson[a-z]0i\r\nsonyericssonj0i0\r\nSonyEricssonJ0i0/R0CA\r\nSonyEricsson[A-Z]{1,2}0iv?/[A-Z0]{4,5}\r\nalcatel-ot-0\r\nALCATEL_0D/0\r\nOPN-B\r\nTwitter for iPhone\r\nTwitter\r\nfor\r\nACHEETAHI/0\r\nMotoE0\r\nKAZAM\r\n\r\n-- Carriers:\r\nOrange\r\nOrange 0\r\nBOUYGUES 0\r\n0 BOUYGUES\r\nBOUYGUES TELECOM\r\nBySFR\r\nSFR\r\nFREE\r\nAOL 0\r\nAOLBuild 0\r\nQMobile A0\r\nVodafone_0_Blue\r\nVodafone/0/Samsung[A-Z0]+/[A-Z0]+\r\n\r\n-- Consoles:\r\nXbox\r\nPSP\r\nPlayStation Portable\r\nPlayStation Vita 0\r\nPLAYSTATION 0 0\r\nNintendoBrowser/0\\.EU\r\nNintendo WiiU?\r\nNintendo DSi\r\nNintendo 0DS\r\n\r\n-- Mail readers:\r\nThunderbird/0\r\nIceweasel/0\r\nSeaMonkey/0\r\nIceDragon/0\r\nEpiphany/0\r\nOutlook-Express/0\r\n\r\n-- Various signatures:\r\nBingPreview/0b\r\n[Pp]rofile/MIDP-0\r\n[Cc]onfiguration/CLDC-0\r\nProfile/MIDP-0 Configuration/CLDC-0\r\nTECNOT0/wap0_Profile/MIDP-0/CLDC-0/0x0/key\r\nMIDP-0/CLDC-0\r\nMIDP-0\r\nVendorID/0\r\nEdition Campaign 0\r\nSIMBAR Enabled\r\nSIMBAR=0\r\nSIMBAR=\\{[A-F0\\-]+\\}\r\nInfoPath\\.0\r\nRM-0_eu_france_0\r\nssr\r\n\r\n-- Plugins:\r\nMSN Optimized\r\n(?:MSN|msn) OptimizedIE0\r\nOfficeLive(Connector|Patch)\\.0\r\nPaleMoon/0\r\nSilk/0\r\nSilk-Accelerated=(?:true|false)\r\nGSA/0\r\nNP0\r\nFbxQmlTV\r\nUCBrowser/0\r\nUCBrowser/0/0/0/UCWEB\r\nUCBrowser0/0/0/UCWEB\r\nUCWEB/0\r\nUCWEB0/0/0\r\nU0/0\r\nR0 0\r\nSV0\r\nS0 V0\r\nNX/0\r\nJ0ME\r\nJ0ME/MIDP\r\nAskTb[A-Z0\\-]+/0\r\nAskTB0\r\nUNTRUSTED/0\r\nMS-RTC LM 0\r\nWebView/0\r\nBada/0\r\nS0OviBrowser/0\r\nNexPlayer/0\r\nSMM-MMS/0\r\nBrowser/Phantom/V0\r\nNaviWoo0\r\nBrowserMob RBU\r\nSRS_IT_[A-F0]+\r\nBRI/0\r\nArgClrInt/0\r\neSobiSubscriber 0\r\nMcAfee\r\nSMART-TV\r\nNavionicsWebStore\r\nchromeframe/0\r\nSpreadTrum\r\nEasyBits GO v0\r\nWUID=[a-fA-F0]+\r\nWTB=0\r\nyie0\r\nKbd\r\nfeed/0\r\nSiteKiosk 0 Build 0\r\nMTK\r\nDealio Toolbar 0\r\nFunWebProducts\r\n0 Mozart\r\nShopperReports 0\r\ntaptu-downloader\r\nOmnia W\r\nXerox_Win0PWS\r\nE0i\r\nBuild 0 Win0 en-us\r\nAvant TriCore\r\nAvant Browser\r\nRadar (0G|C0e)\r\nPlayBook\r\nQQDownload 0\r\nIE0-0NET.COM-0\r\nUGESV 0\r\nseeearchx?\r\nSeekmo 0\r\nSearchToolbar 0\r\n0 Trophy\r\nTITAN X0e\r\nWanadoo 0\r\nCreative AutoUpdate v0\r\nXM0-0\r\nAndroid_Edition_Starnaute\r\nWWTClient0\r\nZ0m\r\nMK0i\r\nWallaIE0\r\nMaster Laptop HP0b_0pXPFRR0V0\r\nSVCVersion 0\r\nTmstmpExt\r\nCreative ZENcast v0\r\nS.N.O.W.0\r\nPTST 0\r\nHotbar 0\r\nWysigot 0\r\nRadar\r\nSlimBrowser/0\r\nNeoNet 0\r\nTrianon SA\r\nFW 0.p\r\nPolaris 0\r\nBrew 0\r\nMaster Desktop XP-FR-AF V0 R0\r\nST0i\r\nInternet-explorer-STCIA\r\nIE-[A-Z]{4}\r\nqdesk 0\r\nMediaPad_0_Lite\r\nBO0IE0_v0\r\nTSB_CLOUD_COMPANION\r\nFOLIO_AND_A\r\natyinst\r\nLBBROWSER\r\nG0H\r\nMT0i\r\nZTE\r\nZTE U0s\r\nnnv0ext\r\nNetShelter ContentScan\r\nNetFront/0\r\nBrowser/NetFront/0\r\nNAVER\r\ninapp search 0 0\r\nYaBrowser/0\r\nimgsizer\r\nPuffin/0[A-Z]{2}\r\nAlexaToolbar/[a-z]+-0\r\nRockMelt/0\r\nwebissimo0/0 svn0b0\r\nNextreaming\r\nIron/0\r\nPhantomJS/0\r\n0gpp-gba\r\nSHP/VPP/R0\r\nTelecaBrowser/Q0C0-0\r\nTINNO0_W0B_HW.+\r\nSplashtop-v0\r\nMQQBrowser/0\r\nFireDownload/0\r\nShopperReports\r\n0P_UVRMFR/0\r\neSafeUser=[A-Za-z_/\\-]+\r\nBrowserNG/0\r\nObigoInternetBrowser/Q0C\r\nTeleca/WAP0\r\nObigo/WAP0\r\nEdition Next\r\nPixi/0\r\nSquider/0\r\nWebClip/0\r\nDorado WAP-Browser/0\r\nPre/0\r\nSeries0/0\r\nMultiLang\r\nCoast/0\r\nBMID/[A-F0]+\r\nZTE S0/0\r\nThreadx/0\r\nMocor/W0\r\nRealease/0\r\nBrowser/Dorado0\r\nChromePlus/0\r\nCFNetwork/0\r\nDarwin/0\r\nwOSBrowser/0\r\nUP\\.Browser/0\\.c\\.0\r\nTouchPad/0\r\nXpressMusicUCBrowser/0/0/0/UCWEB\r\nMAUI WAP Browser\r\nJasmine/0\r\ngeneral\\.useragent\\.override 0\r\nBrowser/Obigo-Q0\r\nMediaPlayer/LGPlayer/0\r\nMMP/0\r\nWaterfox/0\r\nAdventurer/0\r\ngoogleweblight\r\nEvaliant\r\nWPDesktop\r\nThunder 0W\r\nwpif\r\n\r\n-- Strange signature:\r\nFBAN/FBIOS\r\nFBAV/0\r\nFBBV/0\r\nFBDV/iPad0,0\r\nFBMD/iPad\r\nFBMD/iPhone\r\nFBSN/iPhone OS\r\nFBDV/iPhone0\r\nFBSV/0\r\nFBSS/0\r\nFBCR/\r\nFBCR/OrangeFrance\r\nFBCR/Free\r\nFBCR/SFR\r\nFBID/tablet\r\nFBLC/fr_FR\r\nFBLC/f\r\nFBOP/0\r\nFBID/phone\r\n', ''),
(2, 'Unknown bots', '', ''),
(3, 'Browsers with bot-alike signature', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows 0; MSIECrawler)', ''),
(5, 'Fake bots', 'Googlebot\r\nGooglebot-Image/0.0 ASProxy/0.0b0\r\nMozilla/0.0 (compatible; Googlebot/0.0; compatible; Googlebot/0.0; +http://www.google.com/bot.html)\r\nGooglebot/0.0; +http://www.google.com/bot.html)\r\nGooglebot/0.0 (+http://www.googlebot.com/bot.html)\r\nMozilla/0.0 (compatible; Crawler; MSIE 0.0; Windows NT 0.0; SV0; .NET CLR 0.0.0)\r\n<a href=''http://www.g0g0e.net''>spam bot</a> (support@g0g0e.net)\r\n<a href=''http://www.g0g0e.net''>spam bot</a> support@g0g0e.net\r\nMozilla/0.0 (compatible; GoogleApps script; +http://script.google.com/bot.html)\r\nMSNBot/Nutch-0.0.0\r\nMozilla/0.0 (compatible; Googlebot/0.0; +http://www.google.com/bot.html) SafeProxy/0.0b0', ''),
(10, 'Google', 'Googlebot/0.0 (+http://www.google.com/bot.html)\r\nMozilla/0.0 (compatible; Googlebot/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (compatible; Googlebot/0.0; http://www.google.com/bot.html)\r\nMozilla/0.0 AppleWebKit/0.0 (KHTML, like Gecko; compatible; Googlebot/0.0; +http://www.google.com/bot.html) Safari/0.0\r\nMozilla/0.0 (iPhone; U; CPU iPhone OS 0_0 like Mac OS X; 0) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0.0 Mobile/0B0 Safari/0.0.0 (compatible; Googlebot-Mobile/0.0; +http://www.google.com/bot.html)', 'http://www.google.com/bot.html'),
(11, 'Google News', 'Googlebot-News', 'http://www.google.com/bot.html'),
(12, 'Google Image', 'Googlebot-Image/0.0', 'http://www.google.com/bot.html'),
(13, 'Google Video', 'Googlebot-Video/0.0', 'http://www.google.com/bot.html'),
(14, 'Google Mobile', 'Mozilla/0.0 (iPhone; CPU iPhone OS 0_0 like Mac OS X) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0 Mobile/0A0e Safari/0.0 (compatible; Googlebot-Mobile/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (iPhone; U; CPU iPhone OS 0_0 like Mac OS X; en-us) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0.0 Mobile/0B0 Safari/0.0.0 (compatible; Googlebot-Mobile/0.0; +http://www.google.com/bot.html)\r\nDoCoMo/0.0 N0i(c0;TB;W0H0) (compatible; Googlebot-Mobile/0.0; +http://www.google.com/bot.html)\r\nSAMSUNG-SGH-E0/0.0 Profile/MIDP-0.0 Configuration/CLDC-0.0 UP.Browser/0.0.0.0.c.0.0 (GUI) MMP/0.0 (compatible; Googlebot-Mobile/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (iPhone; CPU iPhone OS 0_0 like Mac OS X) AppleWebKit/0.0.0 (KHTML, like Gecko) Version/0.0 Mobile/0F0 Safari/0.0.0 (compatible; Googlebot/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (iPhone; CPU iPhone OS 0_0 like Mac OS X) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0 Mobile/0F0 Safari/0.0.0 (compatible; Googlebot/0.0; +http://www.google.com/bot.html)', 'http://www.google.com/bot.html'),
(15, 'Google AdSense', 'Mediapartners-Google\r\nMozilla (compatible; Mediapartners-Google/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (iPhone; U; CPU iPhone OS 0_0 like Mac OS X; en-us) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0.0 Mobile/0B0 Safari/0.0.0 (compatible; Mediapartners-Google/0.0; +http://www.google.com/bot.html)\r\nMozilla/0.0 (iPhone; U; CPU iPhone OS 0_0 like Mac OS X; 0) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0.0 Mobile/0B0 Safari/0.0.0 (compatible; Mediapartners-Google/0.0; +http://www.google.com/bot.html)', 'http://www.google.com/bot.html'),
(16, 'Google AdWords', 'AdsBot-Google (+http://www.google.com/adsbot.html)\nAdsBot-Google-Mobile (+http://www.google.com/mobile/adsbot.html) Mozilla (iPhone; U; CPU iPhone OS 0 0 like Mac OS X) AppleWebKit (KHTML, like Gecko) Mobile Safari', ''),
(17, 'Google (Page Speed/Producer/Web Snippet)', 'Mozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0 (KHTML, like Gecko; Google Page Speed Insights) Chrome/0.0.0 Safari/0.0 GoogleBot/0.0\r\nGoogleProducer; (+http://goo.gl/0y0SX)\r\nMozilla/0.0 (Windows NT 0.0; rv:0.0) Gecko/0 Firefox/0.0 Google (+https://developers.google.com/+/web/snippet/)', 'http://www.google.com/'),
(18, 'Google (Feedfetcher)', 'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 0 subscribers; feed-id=0)\r\nMozilla/0.0 (compatible) Feedfetcher-Google; (+http://www.google.com/feedfetcher.html)\r\nFeedfetcher-Google; (+http://www.google.com/feedfetcher.html; feed-id=0)\r\nMozilla/0 Feedfetcher-Google;(+http://www.google.com/feedfetcher.html)\r\nMozilla/0.0 (compatible) Feedfetcher-Google;(+http://www.google.com/feedfetcher.html)', 'http://www.google.com/feedfetcher.html'),
(19, 'Google (Web Preview/Wireless Transcoder/Desktop)', 'Mozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0 (KHTML, like Gecko; Google Web Preview) Chrome/0.0.0 Safari/0.0\r\nMozilla/0.0 (en-us) AppleWebKit/0.0 (KHTML, like Gecko; Google Wireless Transcoder) Chrome/0.0.0 Safari/0.0\r\nMozilla/0.0 (compatible; Google Desktop/0.0.0.0; http://desktop.google.com/)', 'https://support.google.com/webmasters/answer/1062498?hl=en'),
(20, 'Bing (MSN)', 'Mozilla/0.0 (compatible; bingbot/0.0; +http://www.bing.com/bingbot.htm)\r\nmsnbot/0.0b (+http://search.msn.com/msnbot.htm)\r\nMozilla/0.0 (iPhone; CPU iPhone OS 0_0 like Mac OS X) AppleWebKit/0.0.0 (KHTML, like Gecko) Version/0.0 Mobile/0A0 Safari/0.0 (compatible; bingbot/0.0; http://www.bing.com/bingbot.htm)\r\nMozilla/0.0 (iPhone; CPU iPhone OS 0_0 like Mac OS X) AppleWebKit/0.0.0 (KHTML, like Gecko) Version/0.0 Mobile/0A0 Safari/0.0 (compatible; bingbot/0.0; +http://www.bing.com/bingbot.htm)', 'http://search.msn.com/msnbot.htm'),
(21, 'Bing (Images)', 'msnbot-media/0.0 (+http://search.msn.com/msnbot.htm)\r\nmsnbot-media/0.0b (+http://search.msn.com/msnbot.htm)\r\n"Mozilla/0.0 compatible MSIE 0.0 Windows NT 0.0 WOW0 Trident/0.0 MsnBot-Media /0.0b"\r\n"Mozilla/0.0 (Windows NT 0.0; WOW0) AppleWebKit/0+ (KHTML, like Gecko) MsnBot-Media /0.0b"\r\nMozilla/0.0 (Windows NT 0.0; WOW0) AppleWebKit/0+ (KHTML, like Gecko) MsnBot-Media /0.0b', 'http://search.msn.com/msnbot.htm'),
(22, 'Bing (News)', 'msnbot-NewsBlogs/0.0b (+http://search.msn.com/msnbot.htm)', 'http://search.msn.com/msnbot.htm'),
(23, 'Windows RSS Platform', 'Windows-RSS-Platform/0.0 (MSIE 0.0; Windows NT 0.0)', 'http://blogs.msdn.com/b/rssteam/archive/2006/04/28/586220.aspx'),
(24, 'Bing (Preview for Windows 8)', 'Mozilla/0 AppleWebKit/0+ (KHTML, like Gecko) BingPreview/0b', 'http://www.bing.com/community/site_blogs/b/webmaster/archive/2012/10/26/page-snapshots-in-bing-windows-8-app-to-bring-new-crawl-traffic-to-sites.aspx'),
(30, 'Voila', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows CE; PPC; 0x0; SPV M0; OpVer 0.0.0.0) VoilaBot BETA 0.0 (support.voilabot@orange-ftgroup.com)\r\nMozilla/0.0 (iPhone; U; CPU iPhone OS 0_0 like Mac OS X; fr-fr) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0.0 Mobile/ 0A0 Safari/ VoilaBot BETA 0.0 (support.voilabot@orange-ftgroup.com)\r\nMozilla/0.0 (Linux; U; Android 0.0.0; GT-S0 Build/GINGERBREAD) AppleWebKit/0.0 (KHTML, like Gecko) Version/0.0 Mobile Safari/0.0 VoilaBot BETA 0.0 (support.voilabot@orange-ftgroup.com)\r\nMozilla/0.0 (Windows; U; Windows NT 0.0; fr; rv:0.0.0) VoilaBot BETA 0.0 (support.voilabot@orange-ftgroup.com)\r\nMozilla/0.0 (Windows; U; Windows NT 0.0;fr;rv:0.0.0) VoilaBotCollector BETA 0.0 (http://www.voila.com/)', 'http://www.voila.com/'),
(40, 'Yandex (Images)', 'Mozilla/0.0 (compatible; YandexImages/0.0; +http://yandex.com/bots)', 'http://yandex.com/bots'),
(41, 'Yandex', 'Mozilla/0.0 (compatible; YandexBot/0.0; +http://yandex.com/bots)', 'http://yandex.com/bots'),
(42, 'Yandex (Image resizer)', 'Mozilla/0.0 (compatible; YandexImageResizer/0.0; +http://yandex.com/bots)', 'http://yandex.com/bots'),
(43, 'Yandex (Direct)', 'Mozilla/0.0 (compatible; YandexDirect/0.0; +http://yandex.com/bots)', 'http://yandex.com/bots'),
(50, 'Exalead', 'Mozilla/0.0 (compatible; Exabot/0.0; +http://www.exabot.com/go/robot)\nMozilla/0.0 (compatible; Exabot/0.0 (BiggerBetter); +http://www.exabot.com/go/robot)', 'http://www.exalead.com/'),
(51, 'Exalead (Images)', 'Mozilla/0.0 (compatible; Konqueror/0.0; Linux) KHTML/0.0.0 (like Gecko) (Exabot-Thumbnails)', 'http://www.exalead.com/'),
(60, 'Ezooms', 'Mozilla/0.0 (compatible; Ezooms/0.0; ezooms.bot@gmail.com)', ''),
(70, 'Trendiction', 'Mozilla/0.0 (Windows; U; Windows NT 0.0; rv:0.0; trendictionbot0.0.0; trendiction search; http://www.trendiction.de/bot; please let us know of any problems; web at trendiction.com) Gecko/0 Firefox/0.0.0.0', 'http://www.trendiction.de/bot'),
(80, 'Archive.org', 'Mozilla/0.0 (compatible; special_archiver/0.0.0 +http://www.archive.org/details/archive.org_bot)\nMozilla/0.0 (compatible; archive.org_bot +http://archive.org/details/archive.org_bot)\nMozilla/0.0 (compatible; archive.org_bot +http://www.archive.org/details/archive.org_bot)\nMozilla/0.0 (compatible; archive.org_bot; Wayback Machine Live Record; +http://archive.org/details/archive.org_bot)', 'http://archive.org/details/archive.org_bot'),
(90, 'Skim', 'SkimBot/0.0 (www.skimlinks.com <dev@skimlinks.com>)', 'http://www.skimlinks.com/'),
(100, 'Proximic', 'Mozilla/0.0 (compatible; proximic; +http://www.proximic.com/info/spider.php)', ''),
(110, 'Baidu', 'Mozilla/0.0 (compatible;Baiduspider/0.0;+http://www.baidu.com/search/spider.html)\r\nMozilla/0.0 (compatible; Baiduspider/0.0; +http://www.baidu.com/search/spider.html)\r\nMozilla/0.0 (Linux;u;Android 0.0.0;zh-cn;) AppleWebKit/0.0 (KHTML,like Gecko) Version/0.0 Mobile Safari/0.0 (compatible; +http://www.baidu.com/search/spider.html)\r\nBaiduspider+(+http://www.baidu.com/search/spider.htm)\r\nMozilla/0.0 (compatible; Baiduspider-cpro; +http://www.baidu.com/search/spider.html)\r\nBaiduspider (xiaocheng_@0.com)\r\nBaiduspider xiaocheng_@0.com\r\nMozilla/0.0 (compatible; heritrix/0.0.0 +http://www.baidu.com)', 'http://www.baidu.com/search/spider.html'),
(111, 'Baidu Image', 'Baiduspider-image+(+http://www.baidu.com/search/spider.htm)', ''),
(120, 'Ahrefs', 'Mozilla/0.0 (compatible; AhrefsBot/0.0; +http://ahrefs.com/robot/)', 'http://ahrefs.com/robot/'),
(121, 'Ahrefs (Fresh pages)', 'Mozilla/0.0 (compatible; AhrefsBot.FreshPages/0.0; +http://ahrefs.com/robot/)', 'http://ahrefs.com/robot/'),
(122, 'Ahrefs (Feeds)', 'AhrefsBot.Feeds v0.0; http://ahrefs.com/', 'http://ahrefs.com/robot/'),
(130, 'Linksmanager', 'LinksManager.com_bot', 'http://linksmanager.com/'),
(140, 'Easou', 'Mozilla/0.0 (compatible; EasouSpider; +http://www.easou.com/search/spider.html)', ''),
(150, 'FeedBot', 'FeedBot', 'http://swdouglass.com/wiki/Wiki.jsp?page=FeedBot'),
(160, 'Crystal Semantics', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; SV0; CrystalSemanticsBot http://www.crystalsemantics.com/user-agent/)', ''),
(170, 'Linkfluence (kraken)', 'Mozilla/0.0 (compatible; Kraken/0.0; http://linkfluence.net/; bot@linkfluence.net)', ''),
(180, 'SuperFeedr', 'Superfeedr bot/0.0 http://superfeedr.com - Make your feeds realtime: get in touch!', ''),
(190, 'Majestic12', 'Mozilla/0.0 (compatible; MJ0bot/v0.0.0; http://www.majestic0.co.uk/bot.php?+)', 'http://www.majestic12.co.uk/bot.php'),
(200, 'Solomono', 'Mozilla/0.0 (compatible; SolomonoBot/0.0; +http://www.solomono.ru)', 'http://www.solomono.ru'),
(210, 'Technorati', 'Technoratibot/0.0', ''),
(220, 'Jike', 'Mozilla/0.0 (compatible; JikeSpider; +http://shoulu.jike.com/spider.html)\nMozilla/0.0 (compatible; JikeSpider; +http://www.jike.com/spider.html)', 'http://www.jike.com/spider.html'),
(230, 'Yunyun', 'Mozilla/0.0 (compatible; YYSpider; +http://www.yunyun.com/spider.html)\nMozilla/0.0 (compatible; YRSpider; +http://www.yunyun.com/SiteInfo.php?r=about)', 'http://www.yunyun.com/spider.html'),
(240, 'Sogou', 'Sogou web spider/0.0(+http://www.sogou.com/docs/help/webmasters.htm#0)\nNew-Sogou-Spider/0.0 (compatible; MSIE 0.0; Windows 0)', 'http://www.sogou.com/docs/help/webmasters.htm#07'),
(241, 'Sogou (Images)', 'Sogou Pic Spider/0.0(+http://www.sogou.com/docs/help/webmasters.htm#0)', 'http://www.sogou.com/docs/help/webmasters.htm#07'),
(250, 'BigBad', 'bigbadbot/0.0', ''),
(260, '360spider', 'Mozilla/0.0 (Windows; U; Windows NT 0.0; rv:0.0.0.0) Firefox/0.0.0.0; 0Spider\r\nMozilla/0.0 (Windows; U; Windows NT 0.0; rv:0.0.0.0) Firefox/0.0.0.0 0Spider;\r\nMozilla/0.0 (Windows; U; Windows NT 0.0; ) Firefox/0.0.0.0; 0Spider\r\nMozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; Trident/0.0); 0Spider\r\nMozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; Trident/0.0; SLCC0; .NET CLR 0.0.0; .NET CLR 0.0.0; .NET CLR 0.0.0; Media Center PC 0.0; MDDR; .NET0.0C; .NET0.0E; .NET CLR 0.0.0; Tablet PC 0.0); 0Spider', ''),
(270, 'DomainTools', 'Mozilla/0.0 (Windows; U; Windows NT 0.0; en; rv:0.0.0.0) Gecko/0 Firefox/0.0.0 (.NET CLR 0.0.0) SurveyBot/0.0 (DomainTools)', ''),
(280, 'Wikio (Images)', 'WikioImagesBot 0.0', 'http://www.wikio.com'),
(281, 'Wikio', 'EbuzzingFeedBot 0.0\nEbuzzingFeedBot 0.0 (http://www.wikio.com)\nWikioFeedBot 0.0\nWikioFeedBot 0.0 (http://www.wikio.com)', 'http://www.wikio.com/'),
(290, 'Wasalive', 'Mozilla/0.0 (compatible; WASALive-Bot ; http://blog.wasalive.com/wasalive-bots/)', 'http://blog.wasalive.com/wasalive-bots/'),
(300, 'Soso', 'Mozilla/0.0 (compatible; Sosospider/0.0; +http://help.soso.com/webspider.htm)\nSosospider+(+help.soso.com/webspider.htm)', 'http://help.soso.com/webspider.htm'),
(310, 'Spinn3r', 'Mozilla/0.0 (X0; U; Linux x0_0; 0; rv:0.0.0.0; aggregator:Spinn0r (Spinn0r 0.0); http://spinn0r.com/robot) Gecko/0 Firefox/0.0.0', 'http://spinn3r.com/robot'),
(320, 'Linkody', 'Mozilla/0.0 (compatible; Linkody bot 0.0)', 'http://www.linkody.com/'),
(330, 'Twitter', 'Twitterbot/0.0\r\nTwitterFeed 0', ''),
(340, 'FreeWebMonitoring', 'FreeWebMonitoring SiteChecker/0.0 (+http://www.freewebmonitoring.com/bot.html)', ''),
(350, 'ContextAd', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0;.NET CLR 0.0.0; ContextAd Bot 0.0)\nContextAd Bot 0.0', 'http://www.pulsepoint.com/'),
(360, 'Yesup', 'Mozilla/0.0 (compatible; YesupBot/0.0; +http://www.yesup.net/bot.html)', 'http://www.yesup.net/bot.html'),
(370, 'SocialRadar (infegy)', 'Mozilla/0.0 (compatible; Linux; Socialradarbot/0.0; bot@infegy.com)', 'http://infegy.com/'),
(380, 'news bot', 'Mozilla/0.0 (compatible; news bot /0.0)', ''),
(390, 'Webmeup', 'Mozilla/0.0 (compatible; BLEXBot/0.0; +http://webmeup-crawler.com/)', 'http://webmeup-crawler.com/'),
(400, 'Mail.RU', 'Mozilla/0.0 (compatible; Linux x0_0; Mail.RU_Bot/0.0; +http://go.mail.ru/help/robots)', 'http://go.mail.ru/help/robots'),
(401, 'Mail.RU (Images)', 'Mozilla/0.0 (compatible; Linux x0_0; Mail.RU_Bot/Img/0.0; +http://go.mail.ru/help/robots)', 'http://go.mail.ru/help/robots'),
(410, 'aiHit', 'Mozilla/0.0 (compatible; aiHitBot/0.0; +http://endb-consolidated.aihit.com/)', 'http://endb-consolidated.aihit.com/'),
(420, 'Unister', 'Mozilla/0.0 (compatible; UnisterBot; crawler@unister.de)', 'http://unister.de'),
(430, 'Seo Profiler', 'Mozilla/0.0 (compatible; spbot/0.0; +http://www.seoprofiler.com/bot )\nMozilla/0.0 (compatible; spbot/0.0.0; +http://www.seoprofiler.com/bot )', 'http://www.seoprofiler.com/bot'),
(440, 'Paper.li', 'Mozilla/0.0 (compatible; PaperLiBot/0.0; http://support.paper.li/entries/0-what-is-paper-li)', 'http://support.paper.li/entries/20023257-what-is-paper-li'),
(450, 'LoadTime', 'Mozilla/0.0 (compatible; LoadTimeBot/0.0; +http://www.load-time.com/bot.html)', 'http://www.load-time.com/bot.html'),
(460, 'ShowYou.com', 'ShowyouBot (http://showyou.com/crawler)', 'http://showyou.com/crawler/'),
(470, 'Pipl', 'piplbot\nMozilla/0.0+(compatible;+PiplBot;++http://www.pipl.com/bot/)', 'http://www.pipl.com/bot/'),
(480, 'Tweetmeme', 'Mozilla/0.0 (compatible; TweetmemeBot/0.0; +http://tweetmeme.com/)\r\nMozilla/0.0 (TweetmemeBot/0.0; +http://datasift.com/bot.html) Gecko/0 Firefox/0.0', 'http://datasift.com/bot.html'),
(490, 'Gigablast', 'Gigabot/0.0\nGigabot/0.0 (http://www.gigablast.com/spider.html)', 'http://www.gigablast.com/spider.html'),
(500, 'Searchmetrics', 'Mozilla/0.0 (compatible; SearchmetricsBot; http://www.searchmetrics.com/en/searchmetrics-bot/)', ''),
(510, 'CustomScoop', 'ScooperBot www.customscoop.com', ''),
(520, 'Career-X', 'Mozilla/0.0 (compatible; CareerBot/0.0; +http://www.career-x.de/bot.html)', ''),
(530, 'GrapeShot', 'Mozilla/0.0 (compatible; GrapeshotCrawler/0.0; +http://www.grapeshot.co.uk/crawler.php)', ''),
(540, 'MaxPointInteractive', 'MaxPointCrawler/Nutch-0.0 (maxpoint.crawler at maxpointinteractive dot com)', ''),
(550, 'ExB', 'ExB Language Crawler 0.0.0 (+http://www.exb.de/crawler)', ''),
(560, 'Brandwatch (Magpie)', 'magpie-crawler/0.0 (U; Linux amd0; 0; +http://www.brandwatch.net)', ''),
(570, 'Semantic Visions', 'Mozilla/0.0 (X0; compatible; semantic-visions.com crawler; HTTPClient 0.0)', ''),
(580, 'Blogtop', 'blogtop.us crawler - http://blogtop.us/', ''),
(590, 'Naver (Yeti)', 'Yeti/0.0 (NHN Corp.; http://help.naver.com/robots/)', 'http://help.naver.com/robots/'),
(600, 'Nigma', 'Mozilla/0.0 (compatible; Nigma.ru/0.0; crawler@nigma.ru)', 'nigma.ru'),
(610, 'Youdao', 'Mozilla/0.0 (compatible; YoudaoBot/0.0; http://www.youdao.com/help/webmaster/spider/; )', 'http://www.youdao.com/help/webmaster/spider/'),
(620, 'Radian6', 'R0_CommentReader(www.radian0.com/crawler)\nR0_FeedFetcher(www.radian0.com/crawler)', 'http://www.radian6.com/crawler'),
(630, 'Zum', 'Mozilla/0.0 (compatible; ZumBot/0.0; http://help.zum.com/inquiry)\nZumBot/0.0 (ZUM Search; http://help.zum.com/inquiry)', 'http://help.zum.com/inquiry'),
(640, 'IBM (oBot)', 'Mozilla/0.0 (compatible; oBot/0.0.0; +http://filterdb.iss.net/crawler/)', 'http://filterdb.iss.net/crawler/'),
(650, 'Newsle', 'Mozilla/0.0 (compatible; newslebot/0.0; +http://newsle.com)', 'http://newsle.com/'),
(660, 'WeSee', 'WeSEE:Search/0.0 (Alpha, http://www.wesee.com/en/support/bot/)', 'http://www.wesee.com/en/support/bot/'),
(670, 'WIRE', 'WIRE/0.0 (Linux; x0_0; Bot,Robot,Spider,Crawler)', 'http://www.cwr.cl/projects/WIRE/'),
(680, '200Please', 'Mozilla/0.0 (compatible; 0PleaseBot/0.0; +http://www.0please.com/bot)', 'http://www.200please.com/bot'),
(690, 'Linkdex', 'Mozilla/0.0 (compatible; linkdexbot/0.0; +http://www.linkdex.com/about/bots/)', 'http://www.linkdex.com/about/bots/'),
(700, 'Alexa (ia_archiver)', 'ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)', 'http://www.alexa.com/site/help/webmasters'),
(710, 'Netopian', 'Crawler for Netopian (http://www.netopian.co.uk/)', 'http://www.netopian.co.uk/'),
(720, 'Crawler4J', 'crawler0j (http://code.google.com/p/crawler0j/)', 'http://code.google.com/p/crawler4j/'),
(730, 'Bixo', 'Mozilla/0.0 (compatible; pub-crawler; +http://wiki.github.com/bixo/bixo/bixocrawler; bixo-dev@yahoogroups.com)\nMozilla/0.0 (compatible; BIXOCRAWLER; +http://wiki.github.com/bixo/bixo/bixocrawler; bixo-dev@yahoogroups.com)', 'http://wiki.github.com/bixo/bixo/bixocrawler'),
(740, 'Attentio', 'Attentio/Nutch-0.0-dev (Attentio''s beta blog crawler; www.attentio.com; info@attentio.com)', 'http://www.attentio.com/'),
(750, 'Netseer', 'Mozilla/0.0 (compatible; Netseer crawler/0.0; +http://www.netseer.com/crawler.html; crawler@netseer.com)\nMozilla/0.0 (compatible; NetSeer crawler/0.0; +http://www.netseer.com/crawler.html; crawler@netseer.com)', 'http://www.netseer.com/crawler.html'),
(760, 'YisouSpider', 'YisouSpider', ''),
(770, 'Lifer', 'Mozilla/0.0 (compatible; LiferBot/0.0)', ''),
(780, 'Sistrix', 'Mozilla/0.0 (compatible; SISTRIX Crawler; http://crawler.sistrix.net/)', 'http://crawler.sistrix.net/'),
(790, 'SEO Engine', 'SEOENGWorldBot/0.0 (+http://www.seoengine.com/seoengbot.htm)', 'http://www.seoengine.com/seoengbot.htm'),
(800, 'Sensika', 'SensikaBot/x.0 (+http://sensika.com)', 'http://sensika.com/'),
(810, 'Sklik', 'SklikBot/0.0 (sklik@firma.seznam.cz;+http://napoveda.sklik.cz/)', 'http://napoveda.sklik.cz/'),
(820, 'TweetedTimes', 'Mozilla/0.0 (compatible; TweetedTimes Bot/0.0; +http://tweetedtimes.com)', 'http://tweetedtimes.com/'),
(830, 'Mojeek', 'Mozilla/0.0 (compatible; MojeekBot/0.0; http://www.mojeek.com/bot.html)', 'http://www.mojeek.com/bot.html'),
(840, 'MetaGenerator', 'MetaGeneratorCrawler/0.0 (www.metagenerator.info)\nMetaGeneratorCrawler/0.0.0 (www.metagenerator.info)', 'http://www.metagenerator.info/'),
(850, 'BNF', 'Mozilla/0.0 (compatible; bnf.fr_bot; +http://www.bnf.fr/fr/outils/a.dl_web_capture_robot.html)', 'http://www.bnf.fr/fr/outils/a.dl_web_capture_robot.html'),
(860, 'Affectv', 'Affectv Robot v0.0/Nutch-0.0 (http://www.affectv.co.uk; austin at affectv dot co dot uk)', 'http://www.affectv.co.uk/'),
(870, 'LinksCrawler', 'LinksCrawler 0.0beta', ''),
(880, 'UberMetrics', 'Mozilla/0.0 (compatible; uMBot-LN/0.0; mailto: crawling@ubermetrics-technologies.com)', 'http://ubermetrics-technologies.com/'),
(890, 'PagesInventory', 'PagesInventory (robot http://www.pagesinvenotry.com)\nPagesInventory (robot http://www.pagesinventory.com)\nPagesInventory (robot +http://www.pagesinventory.com)', 'http://www.pagesinventory.com/'),
(900, 'Moz', 'rogerbot/0.0 (http://moz.com/help/pro/what-is-rogerbot-, rogerbot-crawler+shiny@moz.com)\nrogerbot/0.0 (http://www.moz.com/dp/rogerbot, rogerbot-crawler@moz.com)', 'http://moz.com/help/pro/what-is-rogerbot-'),
(910, 'Phantom.js', 'Phantom.js bot', 'http://phantomjs.org/'),
(920, 'Adnorm', 'AdnormCrawler www.adnorm.com/crawler', 'http://www.adnorm.com/crawler/'),
(930, 'Bit.ly', 'bitlybot/0.0\nbitlybot', 'http://bit.ly/'),
(940, 'Fyber', 'FyberSpider/0.0 (http://www.fybersearch.com/fyberspider.php)', 'http://www.fybersearch.com/fyberspider.php'),
(950, 'PMoz', 'Mozilla/0.0 (compatible; pmoz.info ODP link checker; +http://pmoz.info/doc/botinfo.htm)', 'http://pmoz.info/doc/botinfo.htm'),
(960, 'Wotbox', 'Wotbox/0.0 (+http://www.wotbox.com/bot/)', 'http://www.wotbox.com/bot/'),
(970, 'AnalyticsSEO', 'Curious George - www.analyticsseo.com/crawler', 'http://www.analyticsseo.com/crawler'),
(980, 'Komodia', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0) KomodiaBot/0.0\nMozilla/0.0 (Windows NT 0.0; Win0; x0) KomodiaBot/0.0', 'http://www.komodia.com/'),
(990, 'NetResearchServer', 'nrsbot/0', 'http://www.loopip.com/'),
(1000, 'Wise Guys', 'Mozilla/0.0 (compatible; Vagabondo/0.0; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/)\r\nMozilla/0.0 (compatible; Vagabondo/0.0; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/; http://www.wise-guys.nl/)', 'http://www.wise-guys.nl/'),
(1010, 'Tarantula', 'Mozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0 (KHTML, like Gecko) TarantulaBot (Linux x0_0) Webkit/Apple Safari/0.0 Safari/0.0', ''),
(1020, 'Screener', 'ScreenerBot Crawler Beta 0.0 (+http://www.ScreenerBot.com)', 'http://www.screenerbot.com/'),
(1030, 'CMS', 'Mozilla/0.0 (CMS Crawler: http://www.cmscrawler.com)', 'http://www.cmscrawler.com/'),
(1040, 'Wikipedia (DE)', 'German Wikipedia Dead Weblinks Checker Bot; contact: gifti@toolserver.org', 'http://toolserver.org'),
(1050, 'Sblog.cz', 'SeznamBot/0.0 (+http://fulltext.sblog.cz/)\r\nMozilla/0.0 (compatible; SeznamBot/0.0-test0; +http://fulltext.sblog.cz/)\r\nMozilla/0.0 (compatible; Seznam screenshot-generator 0.0; +http://fulltext.sblog.cz/screenshot/)\r\nMozilla/0.0 (compatible; SeznamBot/0.0; +http://fulltext.sblog.cz/)\r\nMozilla/0.0 PhantomJS (compatible; Seznam screenshot-generator 0.0; +http://fulltext.sblog.cz/screenshot/)', 'http://fulltext.sblog.cz/'),
(1060, 'Struct.it', 'Mozilla/0.0 (compatible; Struct.it crawler; +http://struct.it/contacts/)', 'http://struct.it/contacts/'),
(1070, 'Dhoondho', 'Mozilla/0.0 (windows; U; NT0.0; rv:0.0) Gecko/0 - crawler@dhoondho.com', 'http://dhoondho.com/'),
(1080, 'Woobot', 'woobot/0.0', 'http://woobot.com/'),
(1090, 'AppEngine (various websites)', 'maisvalerir_bot/0.0 (+http://www.maisvalerir.com) AppEngine-Google; (+http://code.google.com/appengine; appid: s~maisvalerir)\r\nMozilla/0.0 (Macintosh; Intel Mac OS X 0_0_0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~feedly-nikon)\r\nAppEngine-Google; (+http://code.google.com/appengine; appid: s~stremor-crawler)\r\nroupamoda_bot/0.0 (+http://www.roupamoda.com) AppEngine-Google; (+http://code.google.com/appengine; appid: s~roupamodapt)\r\nAppEngine-Google; (+http://code.google.com/appengine; appid: picoguide)\r\nMozilla/0.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~vodio-app)\r\nMozilla/0.0 (Windows NT 0.0; WOW0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~sauvejonathan)\r\nMozilla/0.0 (Macintosh; Intel Mac OS X 0_0_0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 \r\nAppEngine-Google; (+http://code.google.com/appengine; appid: s~feedly-social)\r\nMozilla/0.0 (Windows NT 0.0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~davysn0)\r\nAppEngine-Google; (+http://code.google.com/appengine; appid: s~cgiproxy0-hrd)', 'http://code.google.com/appengine'),
(1100, 'CompSpy', 'Mozilla/0.0 (compatible; CompSpyBot/0.0; +http://www.compspy.com/spider.html)', 'http://www.compspy.com/spider.html'),
(1110, 'Muso', 'Mozilla/0.0 (compatible; musobot/0.0; info@muso.com; +http://www.muso.com)', 'http://www.muso.com/'),
(1120, 'Yacy', 'yacybot (freeworld-global; x0 Windows XP 0.0; java 0.0.0_0; Europe/fr) http://yacy.net/bot.html\nyacybot (freeworld/global; amd0 Windows 0 0.0; java 0.0.0_0; GMT-0:0/pt) http://yacy.net/bot.html', 'http://yacy.net/bot.html'),
(1130, 'Sputnik', 'Mozilla/0.0 (compatible; SputnikBot/0.0)', 'http://sputnikbot.com/'),
(1131, 'Sputnik (Images)', 'Mozilla/0.0 (compatible; SputnikImageBot/0.0)', 'http://sputnikbot.com/'),
(1140, 'Garlik', 'GarlikCrawler/0.0 (http://garlik.com/, crawler@garlik.com)', 'http://garlik.com/'),
(1150, 'CognitiveSEO', 'Mozilla/0.0 (Windows; U; Windows NT 0.0; rv:0.0.0.0) Gecko/0 Firefox/0.0.0.0 - James BOT - WebCrawler http://cognitiveseo.com/bot.html', 'http://cognitiveseo.com/bot.html'),
(1160, 'EWH', 'EWH/0.0 ROBOT', ''),
(1170, 'Turnitin', 'TurnitinBot/0.0 (http://www.turnitin.com/robot/crawlerinfo.html)', 'http://www.turnitin.com/robot/crawlerinfo.html'),
(1180, 'Aboundex', 'Aboundex/0.0 (http://www.aboundex.com/crawler/)', 'http://www.aboundex.com/crawler/'),
(1190, '80legs', 'Mozilla/0.0 (compatible; 0/0.0; http://www.0legs.com/webcrawler.html;) Gecko/0\nMozilla/0.0 (compatible; 0/0.0; http://www.0legs.com/webcrawler.html) Gecko/0', 'http://www.80legs.com/webcrawler.html'),
(1200, 'JCE (Joomla Extension)', 'BOT/0.0 (BOT for JCE)', ''),
(1210, 'Mignify (IMR)', 'Mozilla/0.0 (compatible; imrbot/0.0.0 +http://www.mignify.com)', 'http://www.mignify.com/'),
(1220, 'Feedage', 'Mozilla/0.0 (compatible; Feedage/0.0; +http://www.feedage.com/bot.php)', 'http://www.feedage.com/bot.php'),
(1230, 'DomainsBot', 'domainsbot (+http://www.domainsbot.com)', 'http://www.domainsbot.com/'),
(1240, 'RavenCrawler', 'RavenCrawler', ''),
(1250, 'QuerySeeker', 'QuerySeekerSpider ( http://queryseeker.com/bot.html )', 'http://queryseeker.com/bot.html'),
(1260, 'ProFound', 'Mozilla/0.0 (compatible; URLAppendBot/0.0; +http://www.profound.net/urlappendbot.html)', 'http://www.profound.net/urlappendbot.html'),
(1270, 'Netarkivet', 'Mozilla/0.0 (compatible; heritrix/0.0.0 +http://netarkivet.dk/webcrawler/)', 'http://netarkivet.dk/webcrawler/'),
(1280, 'BOTW', 'Mozilla/0.0 (compatible; BOTW Spider; +http://botw.org)', 'http://botw.org/'),
(1290, 'Pic Search', 'psbot/0.0 (+http://www.picsearch.com/bot.html)', 'http://www.picsearch.com/bot.html'),
(1300, 'CU Whois', 'bot(www.cuwhois.com)', 'http://www.cuwhois.com/'),
(1310, 'Lumi', 'LumiBot 0.0\nMozilla/0.0 (Macintosh; Intel Mac OS X 0_0_0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 Lumibot/0.0', ''),
(1320, 'ExactSeek', 'ExactSeek Crawler (nutch 0.0)/Nutch-0.0 (ExactSeek Crawler; http://www.exactseek.com)', 'http://www.exactseek.com/'),
(1330, 'Percolate', 'PercolateCrawler/0.0.0 (ops@percolate.com)', 'http://percolate.com/'),
(1340, 'Botje', 'Mozilla/0.0 (compatible; Plukkie/0.0; http://www.botje.com/plukkie.htm)', 'http://www.botje.com/'),
(1350, 'MarketDefender', 'Mozilla/0.0 (compatible; SinaaBot/0.0; +http://www.marketdefender.com/bot.html)', 'http://www.marketdefender.com/bot.html'),
(1360, 'LinkedIn', 'LinkedInBot/0.0 (compatible; Mozilla/0.0; Jakarta Commons-HttpClient/0.0 +http://www.linkedin.com)', 'http://www.linkedin.com/'),
(1370, 'INA', 'Mozilla/0.0 (compatible; INA dlweb; +http://www.institut-national-audiovisuel.fr/collecte-depot-legal-web.html; robot.dlweb@ina.fr)', 'http://www.institut-national-audiovisuel.fr/collecte-depot-legal-web.html'),
(1380, 'RSSing', 'RSSingBot (http://www.rssing.com)', 'http://www.rssing.com/'),
(1390, 'Various Nutch-based spiders', 'NIS Nutch Spider/Nutch-0.0\r\nSpiderbot/Nutch-0.0\r\nAJCrawler/Nutch-0.0\r\ngoliathbot/Nutch-0.0\r\nMyNutchSpider/Nutch-0.0\r\nNutraspace Spider/Nutch-0.0-SNAPSHOT\r\ntbot-nutch/Nutch-0.0', ''),
(1400, 'Yahoo! (Japan)', 'Y!J-PSC/0.0 crawler (http://help.yahoo.co.jp/help/jp/search/indexing/indexing-0.html)\r\nY!J-ASR/0.0 crawler (http://www.yahoo-help.jp/app/answers/detail/p/0/a_id/0/)', 'http://help.yahoo.co.jp/help/jp/search/indexing/indexing-15.html'),
(1401, 'Yahoo! (Slurp)', 'Slurp\r\nMozilla/0.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)\r\nMozilla/0 (Yahoo! Slurp/0; http://help.yahoo.com/help/us/ysearch/slurp)\r\nMozilla/0.0 (compatible; Yahoo! Slurp/0.0; http://help.yahoo.com/help/us/ysearch/slurp)\r\nMozilla/0.0 (compatible; Yahoo! Slurp/0.0; http://help.yahoo.com/help/us/ysearch/slurp) NOT Firefox/0.0', 'http://help.yahoo.com/help/us/ysearch/slurp'),
(1420, 'PHPCrawl', 'PHPCrawl', 'http://cuab.de/'),
(1430, 'MeMoNews', 'MeMoNewsBot/0.0 (http://www.memonews.com/en/crawler)', 'http://www.memonews.com/en/crawler'),
(1440, 'XXX', 'spider/Nutch-0.0.0 (spider; http://www.xxx.com)', 'http://www.xxx.com'),
(1450, 'RSSMicro', 'RSSMicro.com RSS/Atom Feed Robot\nMozilla/0.0 (compatible; RSSMicro.com RSS/Atom Feed Robot)', 'http://rssmicro.com/'),
(1460, 'Hiva', 'hivaBot/hivaBot-0.0', ''),
(1470, 'Looking For It', 'Mozilla/0.0 (compatible; lookingforitbot/v0.0; http://www.lookingforit.net/bot.php?+)', 'http://www.lookingforit.net/bot.php'),
(1480, 'AdBeat', 'adbeat_bot\r\nMozilla/0.0 (X0; U; Linux x0; %lang_code%) adbeat.com/policy Gecko/0 Ubuntu/0.0 (lucid) Firefox/0.0.0 AppleWebKit/0.0 Safari/0.0', 'http://adbeat.com/'),
(1490, 'Zooka', 'Zookabot/0.0;++http://zookabot.com', 'http://zookabot.com/'),
(1500, 'Screaming Frog SEO', 'Screaming Frog SEO Spider/0,0\nScreaming Frog SEO Spider/0.0', 'http://www.screamingfrog.co.uk/seo-spider/'),
(1510, 'DiffBot', 'Mozilla/0.0 (Windows; U; Windows NT 0.0; rv:0.0.0.0) Gecko/0 Firefox/0.0.0 (.NET CLR 0.0.0; Diffbot/0.0; +http://www.diffbot.com)', 'http://www.diffbot.com/'),
(1520, 'WangID', 'Mozilla/0.0 (compatible; WangIDSpider/0.0; +http://www.wangid.com/spider.html)', 'http://www.wangid.com/spider.html'),
(1530, 'Java', 'Java/0\r\nJava/0.0.0_0', 'http://www.oracle.com/us/technologies/java/overview/index.html'),
(1540, 'Goo.ne.jp (ichiro)', 'ichiro/0.0 (http://search.goo.ne.jp/option/use/sub0/sub0-0/)', 'http://search.goo.ne.jp/option/use/sub4/sub4-1/'),
(1550, 'Rankur', 'RankurBot/0.0 (+http://rankur.com)', 'http://rankur.com/'),
(1560, 'Zite (Worio)', 'Mozilla/0.0 (compatible; woriobot +http://worio.com)\nMozilla/0.0 (compatible; woriobot support [at] zite [dot] com +http://zite.com)', 'http://zite.com/'),
(1570, 'CrawlDaddy', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; CrawlDaddy v0.0.0 abot v0.0.0.0 http://code.google.com/p/abot)', ''),
(1580, 'Kalooga', 'Mozilla/0.0 (compatible; KaloogaBot; http://kalooga.com/crawler)', 'http://kalooga.com/crawler/'),
(1590, 'Suma', 'suma spider', ''),
(1600, 'GrowerIdeas', 'GrowerIdeas Crawler/GrowerIdeas-nutch-0.0 (Crawls URLs for indexing content for our new search startup which aims to provide simple and smart search across curated content. For more info please contact helloworld@growerideas.com. If you think', 'http://growerideas.com/'),
(1610, 'Vefsafn.is', 'Mozilla/0.0 (compatible; heritrix/0.0.0-RC0 +http://vefsafn.is/crawler)', 'http://vefsafn.is/crawler/'),
(1630, 'AdSpider', 'Mozilla/0.0 (Windows NT 0.0; Win0; x0) AppleWebKit/0.0 (KHTML, like Gecko) adspider Safari/0.0', ''),
(1640, 'Media Crawler', 'media_crawler/0.0', ''),
(1650, '51bi', 'Mozilla/0.0 (compatible; bjspider/0.0; + http://www.0bi.com/bot.htm)', 'http://www.51bi.com/bot.htm'),
(1660, 'Cliqz', 'Cliqzbot/0.0 (+http://cliqz.com/company/cliqzbot)', 'http://cliqz.com/company/cliqzbot'),
(1670, 'Web CEO', 'Mozilla/0.0 (compatible; web-ceo-online-bot/0.0; +http://online.webceo.com)', 'http://online.webceo.com/'),
(1680, 'Toile', 'Mozilla/0.0 (+http://www.toile.com/) ToileBot/0.0', 'http://www.toile.com/'),
(1690, 'Luminate', 'Mozilla/0.0 (compatible; LuminateBot/0.0; +http://www.luminate.com/bot/)', 'http://www.luminate.com/bot/'),
(1700, 'Meanpath', 'Mozilla/0.0 (compatible; meanpathbot/0.0; +http://www.meanpath.com/meanpathbot.html)', 'http://www.meanpath.com/meanpathbot.html'),
(1710, 'Clarity', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0 ; Claritybot)', ''),
(1720, 'Zemlya', 'ZemlyaCrawl 0.0', ''),
(1730, 'TinEye', 'TinEye/0.0 (http://tineye.com/crawler.html)', 'http://tineye.com/crawler.html'),
(1740, 'Yummy Peach', 'Yummy Peach Spider/Nutch-0.0 (http://www.yummypeach.com; support@yummypeach.com)', 'http://www.yummypeach.com/'),
(1750, 'ShopWiki', 'ShopWiki/0.0 ( +http://www.shopwiki.com/wiki/Help:Bot)', 'http://www.shopwiki.com/wiki/Help:Bot'),
(1760, 'Datagnion', 'datagnionbot (+http://www.datagnion.com/bot.html)', 'http://www.datagnion.com/bot.html'),
(1770, 'CollapsarWEB', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; CollapsarWEB qihoobot@qihoo.net)', 'http://qihoo.net/'),
(1780, 'Ranks.nl (Keyword Density Analyzer)', 'Keyword Density Analyzer v0.0 ( http://www.ranks.nl/tools/spider.html )', 'http://www.ranks.nl/tools/spider.html'),
(1800, 'PureDiscovery (grokkit)', 'grokkit-crawler (pdsupport@purediscovery.com)', 'http://purediscovery.com/'),
(1810, 'Semrush', 'Mozilla/0.0 (compatible; SemrushBot/0.0; +http://www.semrush.com/bot.html)', 'http://www.semrush.com/bot.html'),
(1820, 'Bipartite', 'Bipartite Bot', ''),
(1830, 'Semantissimo (sSearch)', 'ssearch_bot (sSearch Crawler; http://www.semantissimo.de)', 'http://www.semantissimo.de/'),
(1850, 'BacklinkTest', 'BacklinkCrawler (http://www.backlinktest.com/crawler.html)', 'http://www.backlinktest.com/crawler.html'),
(1860, 'Yioop', 'Mozilla/0.0 (compatible; YioopBot; +http://0.0.0.0/bot.php)', 'http://173.13.143.74/bot.php'),
(1870, 'Yoono', 'YoonoCrawler/0.0 (crawler@yoono.com)', 'http://yoono.com/'),
(1880, 'ADmantX', 'ADmantX Platform Semantic Analyzer - ADmantX Inc. - www.admantx.com - support@admantx.com', 'http://www.admantx.com/'),
(1890, 'Feedly', 'Feedly/0.0 (+http://www.feedly.com/fetcher.html; like FeedFetcher-Google)', 'http://www.feedly.com/fetcher.html'),
(1900, 'Facebook (ExternalHit)', 'facebookexternalhit/0.0 (+http://www.facebook.com/externalhit_uatext.php)\r\nfacebookexternalhit/0.0', 'http://www.facebook.com/externalhit_uatext.php'),
(1901, 'Facebook (Platform)', 'facebookplatform/0.0 (+http://developers.facebook.com)', 'http://developers.facebook.com'),
(1910, 'Genieo', 'Mozilla/0.0 (compatible; Genieo/0.0 http://www.genieo.com/webfilter.html)', 'http://www.genieo.com/webfilter.html'),
(1920, 'feedzirra', 'feedzirra http://github.com/pauldix/feedzirra/tree/master', 'http://github.com/pauldix/feedzirra/tree/master'),
(1930, 'MagpieRSS', 'MagpieRSS/0.0 (+http://magpierss.sf.net)', 'http://magpierss.sf.net'),
(1940, 'SimplePie', 'SimplePie/0.0.0-dev (Feed Parser; http://simplepie.org; Allow like Gecko) Build/0\r\nSimplePie/0.0.0 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/0\r\nSimplePie/0.0 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/0', 'http://simplepie.org/'),
(1950, 'Netvibes', 'Netvibes (http://www.netvibes.com/; 0 subscribers; feedID: 0)\r\nNetvibes (http://www.netvibes.com)', 'http://www.netvibes.com/'),
(1960, 'Bloglovin', 'Bloglovin/0.0 (http://www.bloglovin.com; 0 subscribers)\r\nBloglovin/0.0 (http://www.bloglovin.com;', 'http://www.bloglovin.com/'),
(1970, 'FlipboardProxy', 'Mozilla/0.0 (compatible; FlipboardRSS/0.0; +http://flipboard.com/browserproxy)\r\nMozilla/0.0 (Macintosh; U; Intel Mac OS X 0.0; rv:0.0.0) Gecko/0 Firefox/0.0 (FlipboardProxy/0.0; +http://flipboard.com/browserproxy)\r\nMozilla/0.0 (Macintosh; Intel Mac OS X 0.0; rv:0.0) Gecko/0 Firefox/0.0 (FlipboardProxy/0.0; +http://flipboard.com/browserproxy)', 'http://flipboard.com/browserproxy'),
(1980, 'CheckPrivacy', 'http://www.checkprivacy.or.kr:0/RS/PRIVACY_ENFAQ.jsp', 'http://www.checkprivacy.or.kr:6600/RS/PRIVACY_ENFAQ.jsp'),
(1990, 'A6 Corporation', 'A0-Indexer/0.0 (http://www.a0corp.com/a0-web-scraping-policy/)', 'http://www.a6corp.com/a6-web-scraping-policy/'),
(2000, 'Coccoc', 'Mozilla/0.0 (compatible; coccoc/0.0; +http://help.coccoc.com/)', 'http://help.coccoc.com/'),
(2010, 'Youdao (FeedFetcher)', 'Mozilla/0.0 (compatible;YoudaoFeedFetcher/0.0;http://www.youdao.com/help/reader/faq/topic0/;0 subscribers;)', 'http://www.youdao.com/help/reader/faq/topic006/'),
(2020, 'AolReader', 'AolReader/0.0.0 +http://reader.aol.com/', 'http://reader.aol.com/'),
(2030, 'Topsy (Butterfly)', 'Mozilla/0.0 (Macintosh; Butterfly/0.0; +http://labs.topsy.com/butterfly/) Gecko/0 Firefox/0.0.0\r\nMozilla/0.0 (compatible; Butterfly/0.0; +http://labs.topsy.com/butterfly/) Gecko/0 Firefox/0.0.0', 'http://labs.topsy.com/butterfly/'),
(2040, 'JS-Kit URL Resolver', 'JS-Kit URL Resolver, http://js-kit.com/', 'http://js-kit.com/'),
(2050, 'Perl POE::Component::Client', 'POE-Component-Client-HTTP/0.0 (perl; N; POE; en; rv:0.0)', 'http://search.cpan.org/dist/POE/'),
(2060, 'WordPress Desktop', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; Trident/0.0; ARM; Touch; WPDesktop)', 'http://www.wpdesktop.com/'),
(2070, 'Pinterest', 'Pinterest/0.0 +http://pinterest.com/\r\nPinterest/0.0 (+http://www.pinterest.com/)', 'http://pinterest.com/'),
(2080, 'Palkeo (FeedRetriever)', 'Mozilla/0.0 (compatible; FeedRetriever/0.0; +http://feedspot.palkeo.com)', 'http://feedspot.palkeo.com/'),
(2090, 'FeedDemo', 'FeedDemon/0.0 (http://www.feeddemon.com/; Microsoft Windows)', 'http://www.feeddemon.com/'),
(2100, 'Digg (Feed Fetcher)', 'Digg Feed Fetcher 0 (Mozilla/0 (Macintosh) AppleWebKit/0 (KHTML, like Gecko) Version/0 Safari/0)', 'http://digg.com/'),
(2110, 'Instant Mobilizer', 'Mozilla/0 AppleWebKit/0 (KHTML, like Gecko) Chrome/0 Safari/0; Instant Mobilizer; http://www.instantmobilizer.com)\r\nMozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0; Instant Mobilizer; http://www.instantmobilizer.com)', 'http://www.instantmobilizer.com/'),
(2120, 'eCairn', 'Mozilla/0 eCairn-Grabber/0 (+http://ecairn.com/grabber)', 'http://ecairn.com/grabber'),
(2130, 'Rome Client', 'Rome Client (http://tinyurl.com/0t0n) Ver: UNKNOWN', 'http://tinyurl.com/64t5n'),
(2140, 'IceRocket', 'BlogSearch/0 +http://www.icerocket.com/', 'http://www.icerocket.com/'),
(2150, 'Expo9 (AdServer)', 'expo0', 'http://exponential.com/'),
(2160, 'InAGist URL Resolve', 'InAGist URL Resolver (http://inagist.com)', 'http://inagist.com/'),
(2170, 'AndroidDownloadManager', 'AndroidDownloadManager\r\nAndroidDownloadManager/0.0.0 (Linux; U; Android 0.0.0; GT-I0 Build/JDQ0)\r\nAndroidDownloadManager/0.0.0 (Linux; U; Android 0.0.0; PMP0D0G Build/JRO0H)', ''),
(2180, 'Free Video Downloader Lite', 'Free%0Video%0Downloader%0Lite/0.0.0 CFNetwork/0.0.0 Darwin/0.0.0', ''),
(2190, 'ICAP-IOD', 'ICAP-IOD', 'http://secure.onavo.com'),
(2200, 'Nutch', 'Nutch0/Nutch-0', 'http://nutch.apache.org/'),
(2210, 'SiteExplorer', 'Mozilla/0.0 (compatible; SiteExplorer/0.0b; +http://siteexplorer.info/)', 'http://siteexplorer.info/'),
(2220, 'Mon_httpDownload (Perl)', 'Mon_httpDownload /0.0.0libwww-perl/0.0', ''),
(2230, 'Panscient', 'panscient.com', 'http://panscient.com'),
(2240, 'Daumoa', 'Mozilla/0.0 (compatible; MSIE or Firefox mutant; not on Windows server; + http://tab.search.daum.net/aboutWebSearch.html) Daumoa/0.0', 'http://tab.search.daum.net/aboutWebSearch.html'),
(2250, 'Abonti', 'Mozilla/0.0 (compatible; Abonti/0.0 - http://www.abonti.com)', 'http://www.abonti.com'),
(2260, 'WSCheck', 'wscheck.com/0.0.0 (+http://wscheck.com/)', 'http://wscheck.com/'),
(2270, 'Embedly', 'Mozilla/0.0 (compatible; Embedly/0.0; snap; +http://support.embed.ly/)', 'http://support.embed.ly/'),
(2280, 'CybEye', 'CybEye.com/0.0 (compatible; MSIE 0.0; Windows NT 0.0; Trident/0.0; GTB0.0)', 'http://cybeye.com/'),
(2290, 'CommonCrawl', 'Mozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; WOW0; Trident/0.0) commoncrawl.org/research//Nutch-0.0-SNAPSHOT', 'http://commoncrawl.org/research/'),
(2300, 'Moreover', 'Mozilla/0.0 Moreover/0.0 (+http://www.moreover.com; webmaster@moreover.com)', 'http://www.moreover.com/'),
(2310, 'FeedBlitz', 'FeedBlitz/0.0 (0 subscribers)', 'http://www.feedblitz.com/'),
(2320, 'RebelMouse', 'RebelMouse/0.0 Mozilla/0.0 (compatible; http://rebelmouse.com) Gecko/0 Firefox/0.0.0', 'http://rebelmouse.com/'),
(2330, 'EntireWeb (Speedy Spider)', 'Speedy Spider (http://www.entireweb.com)', 'http://www.entireweb.com/'),
(2340, 'Curl (Linux command-line)', 'curl/0.0.0', 'http://curl.haxx.se/'),
(2350, 'HeyFeed', 'Mozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 HeyFeed/0.0 (+http://www.heyfeed.com/)', 'http://www.heyfeed.com/'),
(2360, 'GetPrismatic', 'Mozilla/0.0 (Macintosh; Intel Mac OS X 0_0_0) AppleWebKit/0.0 (KHTML, like Gecko) Contact: feedback@getprismatic.com', 'http://getprismatic.com/'),
(2370, 'InoReader', 'Mozilla/0.0 (compatible; inoreader.com-like FeedFetcher-Google)', 'http://inoreader.com/'),
(2380, 'PatchOne', 'Mozilla/0.0 (compatible; POGS/0.0; http://www.patchone.se)', 'http://www.patchone.se/'),
(2390, 'BUbiNG', 'BUbiNG (+http://law.di.unimi.it/BUbiNG.html)', 'http://law.di.unimi.it/BUbiNG.html'),
(2400, 'ImmediateN (Thumbnail API)', 'Mozilla/0.0 (X0; Linux x0_0) AppleWebKit/0.0+ (KHTML, like Gecko) Chromium/0.0.0.0 Chrome/0.0.0.0 Safari/0.0+; (+http://immediatenet.com/thumbnail_api.html; free thumbnails)', 'http://immediatenet.com/thumbnail_api.html'),
(2410, 'BlogScope', 'Mozilla/0.0 (compatible; BlogScope/0.0; +http://www.blogscope.net/; U of Toronto)', 'http://www.blogscope.net/'),
(2420, 'Monoid (Web-Monitoring)', 'Mozilla/0.0 (compatible; Web-Monitoring/0.0; +http://monoid.nic.ru/)', 'http://monoid.nic.ru/'),
(2430, 'Dotbot', 'Mozilla/0.0 (compatible; DotBot/0.0; http://www.opensiteexplorer.org/dotbot, help@moz.com)', 'http://www.opensiteexplorer.org/dotbot'),
(2450, 'OrangeBot', 'Mozilla/0.0 (compatible; OrangeBot/0.0; support.orangebot@orange.com)', 'http://orange.com'),
(2460, 'XaxisSemanticsClassifier by Crystalsemantics.com', 'Mozilla/0.0 (Windows NT 0.0; WOW0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0 XaxisSemanticsClassifier/0.0 http://crystalsemantics.com', 'http://crystalsemantics.com');
INSERT IGNORE INTO `BOTSECTOR_CRAWLERS` (`BCR_ID`, `BCR_NAME`, `BCR_SIGNATURE`, `BCR_WEBSITE`) VALUES
(2470, 'ltx71', 'ltx0 - (http://ltx0.com/)', 'http://ltx71.com/'),
(2480, 'HaosouSpider', 'Mozilla/0.0 (Windows NT 0.0) AppleWebKit/0.0 (KHTML, like Gecko) Chrome/0.0.0.0 Safari/0.0; 0Spider(compatible; HaosouSpider; http://www.haosou.com/help/help_0_0.html)\r\nMozilla/0.0 (compatible; MSIE 0.0; Windows NT 0.0; Trident/0.0); 0Spider(compatible; HaosouSpider; http://www.haosou.com/help/help_0_0.html)', 'http://www.haosou.com/help/help_3_2.html'),
(2490, 'Superfeedr', 'Superfeedr bot/0.0 http://superfeedr.com - Make your feeds realtime: get in touch - feed-id:0', 'http://superfeedr.com'),
(2500, 'Qwantify', 'Mozilla/0.0 (compatible; Qwantify/0.0w; +https://www.qwant.com/)/*', 'https://www.qwant.com/'),
(2510, 'Riddler', 'Riddler (http://riddler.io/about)', 'http://riddler.io/about'),
(2520, 'Buzzbot', 'Buzzbot/0.0 (Buzzbot; http://www.buzzstream.com; buzzbot@buzzstream.com)', 'http://www.buzzstream.com'),
(2530, 'HTTrack (Website Copier)', 'Mozilla/0.0 (compatible; HTTrack 0.0x; Windows 0)', 'http://www.httrack.com/'),
(2540, 'WareBay Search Bot', 'Mozilla/0.0 (compatible; WBSearchBot/0.0; +http://www.warebay.com/bot.html)', 'http://www.warebay.com/bot.html'),
(2550, 'Symfony Feed Reader', 'sfFeedReader/0.0', 'https://symfony.com/'),
(2560, 'DuckDuckGo', 'Mozilla/0.0 (compatible; DuckDuckGo-Favicons-Bot/0.0; +http://duckduckgo.com)', 'http://duckduckgo.com'),
(2570, 'XoviBot', 'Mozilla/0.0 (compatible; XoviBot/0.0; +http://www.xovibot.net/)', 'http://www.xovibot.net/'),
(2580, 'TinEye', 'TinEye-bot/0.0 (see http://www.tineye.com/crawler.html)', 'http://www.tineye.com/crawler.html'),
(2590, 'Domain Re-Animator', 'Domain Re-Animator Bot (http://domainreanimator.com) - support@domainreanimator.com', 'http://domainreanimator.com'),
(2600, 'spbot', 'Mozilla/0.0 (compatible; spbot/0.0; +http://OpenLinkProfiler.org/bot )', 'http://OpenLinkProfiler.org/bot'),
(2610, 'DomainAppender', 'Mozilla/0.0 (compatible; DomainAppender /0.0; +http://www.profound.net/domainappender)', 'http://www.profound.net/domainappender'),
(2620, 'Tiny Tiny RSS', 'Tiny Tiny RSS/0.0 (http://tt-rss.org/)', 'http://tt-rss.org/'),
(2630, 'psbot', 'psbot-image (+http://www.picsearch.com/bot.html)', 'http://www.picsearch.com/bot.html');
